kind: pipeline
type: docker
name: default

steps:
- name: installation
  image: python
  commands:
  - pip install numpy
  - pip install python-math

- name: testing
  image: python
  commands:
  - python --version

- name: another testing
  image: python
  commands:
  - pip --version

- name: greeting
  image: python
  commands:
  - python ./1.py
