kind: pipeline
type: docker
name: default

steps:
- name: installation
  image: python
  commands:
  - pip install numpy

- name: ui-testing
  image: python
  commands:
  - python --version

- name: back-testing
  image: python
  commands:
  - pip --version
